# Generated by Django 2.2.6 on 2019-10-07 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugindex',
            old_name='img',
            new_name='image',
        ),
    ]
