# Generated by Django 2.2.2 on 2019-10-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191007_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugindex',
            name='image',
            field=models.TextField(default='', verbose_name='Image'),
        ),
    ]
